name = "SpecialSpaces"
uuid = "cc3e65be-d4cb-4562-9ae2-5262579a9956"
authors = ["Michał Mika <michal@mika.sh>"]
version = "0.2.0"

[deps]
AbstractMappings = "7dac2afd-1bf6-47b8-bc94-9dcdcd19d527"
CartesianProducts = "ddfd9c64-15e7-45fc-8e16-950f3835cae5"
IgaBase = "9c103fa8-ae55-49f5-92db-ab77803cf2c4"
KroneckerProducts = "5766f8de-d509-470a-8420-f491b24ab91b"
SortedSequences = "2f2e3dc8-c2cf-4b7f-b456-36845a1cbdbc"
TensorProductBsplines = "89f2e70f-f704-4f07-9b81-69bdc44074b1"
UnivariateSplines = "2552f6ce-f0d6-4ba3-bf39-bb338613ee69"

[compat]
AbstractMappings = "^0.8.11"
CartesianProducts = "^0.15.2"
IgaBase = "^0.9.0"
KroneckerProducts = "^0.13.1"
SortedSequences = "^0.6.2"
TensorProductBsplines = "^0.8.3"
UnivariateSplines = "^0.15.0"
julia = "^1.10.0"

[extras]
CartesianProducts = "ddfd9c64-15e7-45fc-8e16-950f3835cae5"
KroneckerProducts = "5766f8de-d509-470a-8420-f491b24ab91b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SortedSequences = "2f2e3dc8-c2cf-4b7f-b456-36845a1cbdbc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnivariateSplines = "2552f6ce-f0d6-4ba3-bf39-bb338613ee69"

[targets]
test = ["Test", "SafeTestsets", "CartesianProducts", "KroneckerProducts", "SortedSequences", "UnivariateSplines", "LinearAlgebra"]
