name = "SortedSequences"
uuid = "2f2e3dc8-c2cf-4b7f-b456-36845a1cbdbc"
authors = ["René Hiemstra <rrhiemstar@gmail.com>", "Michał Mika <michal@mika.sh>"]
version = "0.6.2"

[compat]
SafeTestsets = "^0.1.0"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
