name = "BezierBernsteinMethods"
uuid = "e2515d83-272f-46f3-a47f-6d1ac1d67685"
authors = ["René Hiemstra <rrhiemstar@gmail.com>", "Michał Mika <michal@mika.sh>"]
version = "0.2.2"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
IgaBase = "9c103fa8-ae55-49f5-92db-ab77803cf2c4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Combinatorics = "^1.0.3"
IgaBase = "^0.9.0"
SparseArrays = "^1.10.0"
StaticArrays = "^1.9.13"
julia = "^1.10.0"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
